version: "3"

services:
  logic:
    build:
      context: ./sa-logic
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  webapp:
    build:
      context: ./sa-webapp
      dockerfile: Dockerfile
    depends_on:
      - logic
    ports:
      - 8080:8080
    environment:
      - API_HOST=http://logic:5000

  frontend:
    build:
      context: ./sa-frontend
      dockerfile: Dockerfile
    depends_on:
      - webapp
    ports:
      - 3000:80

