apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-logic-deployment
  labels:
    app: sa-logic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-logic
  template:
    metadata:
      labels:
        app: sa-logic
    spec:
      containers:
        - name: sa-logic
          image: studiomj/sa-logic:1.0.0
          ports:
            - containerPort: 5000
