apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-webapp-deployment
  labels:
    app: sa-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-webapp
  template:
    metadata:
      labels:
        app: sa-webapp
    spec:
      containers:
        - name: sa-webapp
          image: sa-webapp:v1.0.0
          env:
            - name: API_HOST
              value: "http://sa-logic-service"
          ports:
            - containerPort: 8080
