apiVersion: v1
kind: Service
metadata:
  name: sa-frontend-service
  labels:
    app: sa-frontend
spec:
  selector:
    app: sa-frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80