apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend-deployment
  labels:
    app: sa-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sa-frontend
  template:
    metadata:
      labels:
        app: sa-frontend
    spec:
      containers:
        - name: sa-frontend
          image: studiomj/sa-frontend:1.0.0
          ports:
            - containerPort: 80
